### ISSUE TITLE
Enhance code completion on/off

### ISSUE THREAD

**Issue by RussellCanfield** [RussellCanfield/wingman-ai-vscode-extension#28]
Code completion currently supports being disabled and enabled. Instead of a disabled option, let’s convert it to always on or hotkey.

**Comment by harlenalvarez** [comment]
PR https://github.com/RussellCanfield/wingman-ai/pull/30

**Comment by harlenalvarez** [comment]
Enhancement has been added to version 0.3.0, the hot key is shift + ctrl + space.  Closing this feature.
