### ISSUE TITLE
Light color theme issue

### ISSUE THREAD

**Issue by tadq** [RussellCanfield/wingman-ai-vscode-extension#37]
Wingman AI generated code barely visible in sidebar when light color theme is used in VS Code.
I have tried few different light themes and all look the same. Bleached.

![Screenshot from 2024-04-25 15-29-25](https://github.com/RussellCanfield/wingman-ai/assets/148455760/88ecbfa7-706d-4c57-be73-c43606a53ade)

**Comment by harlenalvarez** [comment]
I’ll take a look at it

**Comment by harlenalvarez** [comment]
Thanks for the feedback let us know if you have more.
