### ISSUE TITLE
Publish on OpenVSX for VSCodium users

### ISSUE THREAD

**Issue by trymeouteh** [RussellCanfield/wingman-ai-vscode-extension#39]
I use VSCodium, a fully open source fork of VSCode and the extension store for VSCodium is OpenVSX. Please publish and maintain this extension on OpenVSX for us VSCodium users.

https://vscodium.com/
https://open-vsx.org/

**Comment by RussellCanfield** [comment]
We aren’t planning to support codium at this time

**Comment by Huge** [comment]
@RussellCanfield any changes to your plan in the almost-a-year passed? Maybe a .vsix in https://github.com/RussellCanfield/wingman-ai/releases ?

@trymeouteh you possibly know a dirty hack/patch to your installation like https://gitlab.com/-/snippets/4829583 . It was tested to work, just needs sudo when editing the json.
