### ISSUE TITLE
VueJS2 and Linux Bash files not running

### ISSUE THREAD

**Issue by Nerding4life** [RussellCanfield/wingman-ai-vscode-extension#43]
We are having problems with getting wingman with ollama integrated working with .vue and .sh files. We are able to get them to work 
with other filetypes, like .js, .json, and .php to name a few. We run the latter filetypes and we get the greyed out code suggestions and a loading circle on the bottom right hand corner of the screen, but with the former we get no response at all. We are running in a VSCode extension.

**Comment by harlenalvarez** [comment]
Are you having these issues from chat or code complete?

**Comment by Nerding4life** [comment]
Code complete

**Comment by harlenalvarez** [comment]
Cool, I’ll add support for those types tonight.

**Comment by harlenalvarez** [comment]
We've added support for Vuew and Shell, feel free to test it with version 0.3.6

**Comment by Nerding4life** [comment]
Seems to work good! Thank you!

**Comment by Nerding4life** [comment]
Checking in, and seems to be running fine. Some hiccups here and there, but we are going through a bunch of different combos to see how and what works the best. We will let you know if we run into any more problems. The pro AI side of our team has been pretty happy so far!

**Comment by RussellCanfield** [comment]
> Checking in, and seems to be running fine. Some hiccups here and there, but we are going through a bunch of different combos to see how and what works the best. We will let you know if we run into any more problems. The pro AI side of our team has been pretty happy so far!

Glad to hear! If you are able to provide any examples so we can improve certain scenarios we are happy to look!
