### ISSUE TITLE
Not able to run the extension by installing it manually. 

### ISSUE THREAD

**Issue by sickpuppy1** [RussellCanfield/wingman-ai-vscode-extension#50]
i just want to make same UI changes fit my preference by the i tried to install the extension from the repo and ran it, everything worked okay by none of the functions were working like chat or code completion. I have ollama installed too. I am trying this on my macbook m1. perhaps it would be of great help if you could list the steps of installation through this repo instead of VS Code.

**Comment by RussellCanfield** [comment]
Hi,

Currently there is some aggressive validation when it comes to Ollama. Right now the extension saves your settings in your workspace within the “.vscode” folder.

it’s possible those may be set to a model we don’t support - if none of the views load. This is changing soon.

but in the readme in the repo and VSCode market place, it lists models we support. Look for any pop up error dialogs, and under the Output tab in the terminal window there is a Wingman category

**Comment by sickpuppy1** [comment]
![Screenshot 2024-09-23 at 9 12 12 PM](https://github.com/user-attachments/assets/d490b551-e508-49f7-ac17-a276eb76dd7c)
Thanks for replying earlier. 
Hey, I installed all the supported models and did everything exactly and made no changes, but still it's not working.

**Comment by RussellCanfield** [comment]
Interesting, maybe it’s a bug when you have a blank document open. A lot of the extension is based around being in a workspace, do you have a folder open?

**Comment by sickpuppy1** [comment]
https://drive.google.com/file/d/1NcKTbqXFiJn_fC6HG4L4jbSarXuh5CoP/view?usp=sharing
i have recorded exactly what i am doing and spot where it's not working.

**Comment by RussellCanfield** [comment]
Just wanted to check in to see if the latest release has resolved the issues you were running into?

**Comment by sickpuppy1** [comment]
https://drive.google.com/file/d/1hYW9IZFjBQEyLzbyHy_7Gd8xY8PM1e6o/view?usp=sharing
no there are new issues now which I don't seem to have a solution to.

**Comment by RussellCanfield** [comment]
> https://drive.google.com/file/d/1hYW9IZFjBQEyLzbyHy_7Gd8xY8PM1e6o/view?usp=sharing no there are new issues now which I don't seem to have a solution to.

You can see the error message on the bottom right, Wingman currently requires a workspace (folder in VSCode user terms) to be open for it to function. So once you launch the extension, you can just go to File -> Open Folder, and choose a folder. Then you should be able to get past that.

**Comment by RussellCanfield** [comment]
@sickpuppy1 - closing this issue, but you should be able to just run the extension then open a folder and it should work
