### ISSUE TITLE
Index, does it support files other than apps/**/*.{js,jsx,ts,tsx}

### ISSUE THREAD

**Issue by MarkWard0110** [RussellCanfield/wingman-ai-vscode-extension#53]
In the Index configuration, I am trying to change the inclusion filter, but my edits are replaced with `apps/**/*.{js,jsx,ts,tsx}`

I can modify the text in the inclusion filter, but when I stop typing, the edits are replaced with `apps/**/*.{js,jsx,ts,tsx}`

Does the index support a user-defined inclusion filter?

I just installed the extension configured with Ollama chat and embeddings.

**Comment by RussellCanfield** [comment]
Hi Mark,

Yes this is indeed a bug, there is a little state background refresh on the indexer view since the whole panel is never unloaded from memory. I will get a fix out for this shortly.

Thanks for reporting the bug!

**Comment by RussellCanfield** [comment]
This is fixed in release 0.7.11 - it should be available in the next 5-10 minutes, please let me know if you run into any more issues. This area will be enhanced in the next release.

Enhancements:
- Persist filters
- Expose filters after index is created
- Use filters during file save operations

**Comment by RussellCanfield** [comment]
@MarkWard0110 - good to close?

**Comment by RussellCanfield** [comment]
@MarkWard0110 - The update is now released, v0.7.23 should be available shortly. This will now persist the filters on change, and will use the same filters server side when you save documents.
