### ISSUE TITLE
Index, didn't exist until I saved a file

### ISSUE THREAD

**Issue by MarkWard0110** [RussellCanfield/wingman-ai-vscode-extension#54]
I was unable to create an initial index. First, I had to save a file, and then it made an index.
The inclusion configuration is gone.

I am unable to index the complete repository.

**Comment by RussellCanfield** [comment]
Hi Mark,

Yes this is indeed a bug, there is a little state background refresh on the indexer view since the whole panel is never unloaded from memory. I will get a fix out for this shortly. 

Thanks for reporting the bug!

**Comment by RussellCanfield** [comment]
Hi Mark,

Yes index creation happens one of two ways:

1 - A full index build
2- Saving a file with "Embedding Settings" enabled

I am about to release a fix around custom inclusion filters. But this area is getting an upgrade next :). It will persist, and you can modify the filters that will apply during file saving.

**Comment by RussellCanfield** [comment]
@MarkWard0110 - good to close?
