### ISSUE TITLE
Server process exited with code 1

### ISSUE THREAD

**Issue by dsetzer** [RussellCanfield/wingman-ai-vscode-extension#55]
I can't get the extension to start up properly, something with server.js

```
[Error - 6:09:19 AM] Server process exited with code 1.
[Error - 6:09:19 AM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 6:09:19 AM] Connection to server got closed. Server will restart.
true
[Error - 6:09:19 AM] Wingman Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```
It does this about 5 times before giving up and it never loads, the wingman config never loads, the sidebar never loads, it all just remains in a loading state.

Edit: This is happening to me in github codespaces just to be clear, that is mainly the only thing I use is the vscode-insiders within a codespace.

**Comment by RussellCanfield** [comment]
Hi Daniel,

Sorry to hear you’re having issues. Are code spaces the browser based IDE? If you can send over the whole output from Wingman and Wingman Language Server that may help.

if it is the browser version, we may not be compatible.

**Comment by RussellCanfield** [comment]
@dsetzer - are you able to send over the client side logs? I am fairly sure we are not compatible with the web version of VSCode but would like to confirm.

**Comment by RussellCanfield** [comment]
@dsetzer - closing as inactive, let me know if you had other questions
