### ISSUE TITLE
No respose from the wingman chat

### ISSUE THREAD

**Issue by OboMarvin** [RussellCanfield/wingman-ai-vscode-extension#57]
VS code version:
Version: 1.94.2 (user setup)
Commit: 384ff7382de624fb94dbaf6da11977bba1ecd427
Date: 2024-10-09T16:08:44.566Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

Download the models:
deepseek-coder:6.7b-base-q8_0
deepseek-coder:6.7b-instruct-q8_0

Have tested to post  a http request with a question to "http://127.0.0.1:11434//api/generate" and that work

Would be greaeful if you could help out here

**Comment by RussellCanfield** [comment]
Hi,

What are your machine specs? Also, two things to check:

1.) do you have a workspace or folder open?
2.) can you send over any logs from “Output” -> “Wingman” ?

**Comment by OboMarvin** [comment]
Hi,
I have a Windows 11 pro with 32GB of ram and 2 tb hard drive.
I have tested both folder and workspace.

There are nothing in the output  window.

When I ask a question,  the Wingman  respond window start to pulses, but nothing else happens
here is my settings:
![image](https://github.com/user-attachments/assets/0a51cbcb-c1b2-4f5f-acfa-fa4b73577339)

**Comment by RussellCanfield** [comment]
> Hi, I have a Windows 11 pro with 32GB of ram and 2 tb hard drive. I have tested both folder and workspace.
> 
> There are nothing in the output window.
> 
> When I ask a question, the Wingman respond window start to pulses, but nothing else happens here is my settings: ![image](https://private-user-images.githubusercontent.com/49194376/376035652-0a51cbcb-c1b2-4f5f-acfa-fa4b73577339.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjQyMTcsIm5iZiI6MTcyODgyMzkxNywicGF0aCI6Ii80OTE5NDM3Ni8zNzYwMzU2NTItMGE1MWNiY2ItYzFiMi00ZjVmLWFjZmEtZmE0YjczNTc3MzM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEzVDEyNTE1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyYTIxMGZlYjJiMDY5MDMyZGQ0MjY1ODVlMDUxZmQ3YWE1MjVjNjhjZGY3N2YzOGZlZGY5ZmU4Yjc5OWRlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sohgt1mgOJlKvup3yL_V5YgZzG2uSfS8_xi8goEiFc8)

What gpu do you have? Wingman output will log some timings around requests, but if you don’t have a gpu powerful enough to run inference then it may take a while.

There are a few things you can do such as running a q4 model in that case and reducing some settings under interaction settings.

**Comment by OboMarvin** [comment]
NVIDIA RTX A1000 6GB Laptop GPU

**Comment by RussellCanfield** [comment]
Ok so this could be related to the performance of that GPU. Here is how chat works:

In the configuration settings - under Interaction Settings, you can lower the chat context window - this takes effect when you have files open in the editor. It will pull surrounding text from your cursor. In the settings, you can also lower chat max tokens.

if you have embedding enabled, it will use RAG to pull additional context when you use chat.

together they can add a considerable amount of tokens to the prompt which may be the issue.

another trick you can try is just open a file a highlight a small section of text/code. This will bypass pulling surrounding text so it focuses on the highlighted code.

also you only have 6gb of ram, the Deepseek 6.7b model in q8 will require more ram. You can downgrade to a q4 for more performance. But let me know if this helps.

in general performance is based on the amount of tokens passed to the LLM

**Comment by RussellCanfield** [comment]
@OboMarvin - please try with the latest release of v0.7.15, there was a scenario where no embeddings being available would crash the chat response. It should be released in the next 10-15 minutes.

**Comment by OboMarvin** [comment]
Hi @RussellCanfield , 

Just to confirm,  the chat is now responding after your update.

BR
@OboMarvin
