### ISSUE TITLE
WingMan.wing-man-0.7.14.vsix doesn't install properly on VSCodium 

### ISSUE THREAD

**Issue by John-OK** [RussellCanfield/wingman-ai-vscode-extension#58]
When I try to install via this command: codium --install-extension /home/john/Downloads/WingMan.wing-man-0.7.14.vsix, I get three pop up messages:
- The Wingman Language Server server crashed 5 times in the last 3 mintues. The server will not be restarted. See the output for more information;
- Server initialization failed; and
- Pending response rejected since connection got disposed

I checked the output, but it's too long to post here.
- I was coming from Wingman 0.5.2, so I uninstalled, via codium --uninstall-extension /home/john/Downloads/WingMan.wing-man-0.7.14.vsix;
- closed VSCodium;
- removed the Wingman folder from .vscode-oss/extensions;
- cleared loaded models from ollama; and
- tried installing again, but got the same popup messages.
- I also tried installing 0.7.10 (after uninstalling, etc.) to see if an older version would work, but got the same messages.

Any suggestions? If not, how can I get the 0.5.2 .vsix file so I can revert back to that (I no longer have the file I used to install it).
I really hope I can get 0.7.14 to work. I'm looking forward to the new features!

**Comment by RussellCanfield** [comment]
Hey @John-OK - we don’t support Codium at this time. Happy for any contributions around supporting it though!

**Comment by RussellCanfield** [comment]
@John-OK - can before just writing it off as not supported. Could you please check the "Output" section of VSCodium? You should see two sections one for Wingman and one for Wingman Language Server. Output from both would be greatly appreciated.

**Comment by RussellCanfield** [comment]
@John-OK - did you get it to work? If I don't hear back I'll assume it works and close this issue :)

**Comment by John-OK** [comment]
Hi @RussellCanfield - been trying other solutions and just returned here to see if I can get this to work.
You probably already know this, but Codium is VS Code with the telemetry removed. So, I think WingMan should work with it.

I'm attaching the output as it's quite long.
[Output.md](https://github.com/user-attachments/files/17533415/Output.md)

**Comment by RussellCanfield** [comment]
Thanks! That is a large stack trace :) And this happens on the latest version as well right? What OS/Architecture is your machine running?

**Comment by John-OK** [comment]
Yes, that was the output from the latest version of WingMan. I can't get the version that I did have working (0.5.2) as it's no longer available on VS Marketplace. I'm using Pop! OS 22.04 LTS (based on Ubuntu 22.04) on an x64 Intel CPU (i7-3770K).

**Comment by RussellCanfield** [comment]
Ah! We don't support linux at the moment - due to size limitations of VSCode extensions. We use a WASM package that is semi large so we haven't added Linux. But I can provide you instructions for building it locally and adding linux :) Its pretty easy to do.

Edit this file to include the other npm packages for your linux distro - you can search them on npm
https://github.com/RussellCanfield/wingman-ai/blob/32ea5a5baa96075ed82cc88274e0c3e13dba5c24/scripts/build.js#L5

Then run:
"vsce package"

It should create a VSIX at the root of the repo.
