### ISSUE TITLE
Error: AI Provider Ollama is not configured correctly

### ISSUE THREAD

**Issue by ASnowFlaker** [RussellCanfield/wingman-ai-vscode-extension#62]
fresh install Ollama version to date 0.4.1
fresh install VSCode version to date 1.95.3
fresh install Wingman-AI version to date 0.8.6.

![config](https://github.com/user-attachments/assets/3595d5a0-f6c5-453d-9ad2-e9d88a866a2f)

I've also tried Wingman-AI v0.7.36
I've also tried different combinations on a different machine.

Wingman-AI version 0.5.2 with both VSCode v1.95.3 and v1.87.2gives error: `Unable to verify Ollama has code model deepseek-coder:6.7b-base-q8_0, have you pulled the model or is the config wrong?`

**Comment by RussellCanfield** [comment]
Hi,

I think there is a small bug where if you have never physically changed the Ollama model, it defaults.

try to change the code model to another model, save, then change it back. And if that doesn’t work I can take a look further.

thanks

**Comment by RussellCanfield** [comment]
Any luck?

**Comment by craole-cc** [comment]
I'm experiencing the same issue. What was the solution for this? I have 3 models installed and nothing works.

$ ollama list | awk 'NR > 1 {print $1}'
deepseek-coder:6.7b-base-q8_0
nezahatkorkmaz/deepseek-v3:latest
qwen2.5-coder:32b

$ code --version
code 1.96.2 (commit fabdb6a30b49f79a7aba0f2ad9df9b399473380f)

$ code --list-extensions --show-versions | rg "wingman"
wingman.wing-man@0.8.18

![wingman_settings](https://github.com/user-attachments/assets/9876c8fd-768f-44db-8cdc-47ffe371bd9e)

**Comment by RussellCanfield** [comment]
> I'm experiencing the same issue. What was the solution for this? I have 3 models installed and nothing works.
> 
> 
> 
> $ ollama list | awk 'NR > 1 {print $1}'
> 
> deepseek-coder:6.7b-base-q8_0
> 
> nezahatkorkmaz/deepseek-v3:latest
> 
> qwen2.5-coder:32b
> 
> 
> 
> $ code --version
> 
> code 1.96.2 (commit fabdb6a30b49f79a7aba0f2ad9df9b399473380f)
> 
> 
> 
> ![wingman_settings](https://github.com/user-attachments/assets/9876c8fd-768f-44db-8cdc-47ffe371bd9e)
> 
> 

I believe you just have to change the model from the list in the provider. 

There are some logs under Output -> Wingman that may help.

I will try to test this again myself.
