### ISSUE TITLE
[FEATURE REQUEST] Code Completion Tokens Limit

### ISSUE THREAD

**Issue by Usama3627** [RussellCanfield/wingman-ai-vscode-extension#8]
Hi,

I am using Wingman AI on my 2018 Macbook Pro for VSCode. Since it runs `deepseek-coder` on CPU, it takes a while to generate the code. For the autocompletion, on like 1 second pause, I want to see the generated text. 

According to the codebase, the current set token limit is 1024, which is quite high. I want to request it to be user-adjustable, for me, 30-50 tokens would be the best limit and they will get generated in 2 seconds as well. Currently, it takes over 40 seconds to see the autocompletion. That is not practical at all.

Can you please implement it? Thank you!

Secondly, can we make code contributions?

**Comment by RussellCanfield** [comment]
Hi,

Thank you for trying Wingman! I can absolutely add configurable max token counts. Another thing you can try is a lower bit model like the q4 where it’s a little compressed. Another option is using HuggingFace, it’s free and still isn’t quite instant but it won’t be constrained by your hardware, it’s just a setting right now but we only support codellama at the moment which is still decent. 

We are open to contributions but we have some big ideas in flight so some areas may change in upcoming refactors

**Comment by Usama3627** [comment]
Thanks for the quick response. I am already using the q4 model. However, 1024 tokens still take way too much on slightly older hardware. I didn't know about the HuggingFace option. I will test it out. 

Looking forward to the new changes and anyone I can help.

**Comment by RussellCanfield** [comment]
Appreciate it :) I just published version 0.1.2, here are the two new settings:

codeMaxTokens - the maximum number tokens to generate in a single request (default: 1024)
chatMaxTokens - the maximum number tokens to generate in a single request (default: 1024)

Let me know if you run into any issues

**Comment by Usama3627** [comment]
Wow, that was very quick. I just tested it and the time dropped from 40 seconds to around 15 seconds. When I test the model on ollama cli, it generates a lot faster. But on the extension, it still takes 10-15 seconds to generate.

I wonder what could be the issue and how it be solved. I will try to go through the code and see if I can find anything that might be affecting the speed. Maybe the model is getting loaded every time? I have now set the codeMaxTokens to 20.

Thanks for the quick resolution.

**Comment by Usama3627** [comment]
Update:
I went through the code. Noticed the context size was set to 4096 tokens. I tested with same code file on Ollama CLI. I was able to replicate this exact time taken on CLI as well. The bigger the context window, the more time it takes as well.

If it is not much to ask, can you make the context size for the completion model in user user-adjustable setting as well? Thanks!

**Comment by RussellCanfield** [comment]
> Update: I went through the code. Noticed the context size was set to 4096 tokens. I tested with same code file on Ollama CLI. I was able to replicate this exact time taken on CLI as well. The bigger the context window, the more time it takes as well.
> 
> If it is not much to ask, can you make the context size for the completion model in user user-adjustable setting as well? Thanks!

The context window size is to control the size of the prompt, I can make this configurable so you can shrink the context of the models receive. This will result in lower quality code completion though as it will lose the context of the surrounding code. It may offer a performance boost if you shrink it but quality will reduce.

This is on our list to improve, as some models support larger context windows. Let me work on getting this pushed

**Comment by Usama3627** [comment]
Yes, I agree and that's understandable. A bigger context window requires more processing, the default value could be 4096 but it should be user-configurable to adjust for low-end hardware. For example, for me, 300-500 context tokens would be great. Currently, I can't utilize the full potential of this amazing extension.

**Comment by RussellCanfield** [comment]
Ok, we pushed out release 0.1.14, it's a small breaking change to the configurable tokens. But it now includes the ability to trim the context windows and token generated. Check out the documentation, it's publishing now but should take 15-20 minutes to become available:

https://github.com/RussellCanfield/wingman-ai?tab=readme-ov-file#014

**Comment by RussellCanfield** [comment]
@Usama3627 - good to close?

**Comment by Usama3627** [comment]
Yes. Thank you for the implementation. Love using it.
